name = "Industry 4.0 Systems"
#page = "https://www.notion.so/Industry-4-0-Systems-89f2d3ee8c1249b38840f65d9b1ad392"
page = "https://i40sys.notion.site/Industry-4-0-Systems-89f2d3ee8c1249b38840f65d9b1ad392"
#page = "https://i40sys.notion.site/27aea9b713dd4d5999da77fd88986494"
[site]
  [[site.meta]]
  name = "Industry 4.0 Systems"
  content = "Crea tu propio gateway de IoT"
  [[site.meta]]
  name = "description"
  content = ""

  [site.fonts]
  site = 'Offside'
  navbar = 'Offside'
  title = 'Offside'
  h1 = 'Offside'
  h2 = 'Offside'
  h3 = 'Offside'
  body = 'Offside'
  code = 'Offside'

  [[site.inject.head.link]]
  rel="icon" 
  sizes="16x16"
  type="image/png"
  href="favicon-16x16.png"
  
  [[site.inject.body.script]]
  type="text/javascript"
  src="notion-proxy.js"

[pages]
